/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.4.0
 *
 * Project: 'HelloWorld.balanced+CM0' 
 * Target:  'balanced+CM0' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* tensorflow::Machine Learning:TensorFlow:Kernel&Reference@1.24.5-beta1 */
// enabling global pre includes 
        #define TF_LITE_STATIC_MEMORY 1


#endif /* PRE_INCLUDE_GLOBAL_H */
