/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.1.0
 *
 * Project: 'HelloWorld.size+CM55' 
 * Target:  'size+CM55' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* tensorflow::Machine Learning:TensorFlow:Kernel&Reference@1.24.2 */
// enabling global pre includes 
        #define TF_LITE_STATIC_MEMORY 1


#endif /* PRE_INCLUDE_GLOBAL_H */
